name: Flake8

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  flake8-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-cachefile-
        restore-keys: ${{ runner.os }}-cachefile-

    - name: Setup Python 3.7
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Dependencies
      id: setup-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Flake8 Lint
      id: flake8
      run: |
        flake8 . --extend-ignore=E305,E741,W605,E731,E722,F523,F522,F601,F632,F823 --count --show-source --statistics
